### ISSUE TITLE
[Suggestion] Config option to disable "integration"

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/OreExcavationIntegration#1]
For example a modpack "mode" that can also switch configs (theoretically) could have one config where OEI enchant/modifier is needed to use OE, and a second config for a simplified mode where OEI is not needed (same effect as fully disabling the jar, but without messing up item registry or server/client mismatch (fatally missing)

**Comment by BloodWorkXGaming** [comment]
Added both ^^
