### ISSUE TITLE
Feature request to add an option to remove the message when Modifier or Enchant not present

### ISSUE THREAD

**Issue by GrumpyChunks** [AllTheMods/OreExcavationIntegration#2]
Every time I try to mine a ore block with a tinkers pick axe that doesn't have the modified applied, I get the message displayed in chat:

> you need the excavate modifier or the enchantment on your tool to be able to excavate

Could you add an option to disable this message, as it's quite annoying early game when you get started and chat is constantly spammed with this message when you mine ores?

**Comment by BloodWorkXGaming** [comment]
Do you have always excavate activated in the config? But ye, can add a
config for that.

BinaryCrafter <notifications@github.com> schrieb am Di., 24. Okt. 2017,
23:15:

**Comment by GrumpyChunks** [comment]
Yes, always activated, with no modifier on the tinkers tool, the message stops when I finally obtain the resources to apply the tinker's modifier to the pick.

**Comment by GrumpyChunks** [comment]
Thanks for adding this as a config option, much appreciated.
