### ISSUE TITLE
Excavate Modifier/Enchantment broken on version ATM3 4.4

### ISSUE THREAD

**Issue by Boomflex** [AllTheMods/OreExcavationIntegration#3]
https://github.com/AllTheMods/ATM-3/issues/248

**Comment by BloodWorkXGaming** [comment]
Already fixed in dev, just gotta release the version to curse (and new atm3
version)

There was some code changed in ore excavation which broke my stuff.

The Jenkins build should fix it

Boomflex <notifications@github.com> schrieb am Mi., 1. Nov. 2017, 13:36:
