### ISSUE TITLE
Feature request: Support for Enchantment Descriptions

### ISSUE THREAD

**Issue by TheDeviantCrafter** [AllTheMods/OreExcavationIntegration#6]
[Enchantment Descriptions](https://minecraft.curseforge.com/projects/enchantment-descriptions) adds exactly what it says on the tin. I'd like to request support for this mod. The mod's Curseforge explains how this can be done.

**Comment by BloodWorkXGaming** [comment]
Added it, thanks for the suggestion (even tho it was quite a while ago) ^^
